<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SL-1155.local" failures="3" tests="8" name="Command line test" time="143.943" errors="0" timestamp="25 Oct 2019 14:18:01 GMT">
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="23.664"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="26.088"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="30.113"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="84.485">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.Login(WebDemoTest.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="87.626">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.Login(WebDemoTest.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="88.497">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DemoTest.Tests.WebDemoTest.Login(WebDemoTest.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="102.383"/>
  <testcase classname="com.DemoTest.Tests.WebDemoTest" name="Login" time="143.572"/>
</testsuite> <!-- Command line test -->
